version: "3.8"
services:
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nextjs
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: frontend-nextjs
    depends_on:
      - backend
      - postgres-db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "4001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    container_name: backend-nodejs
    depends_on:
      - postgres-db
    networks:
      - app-network

  postgres-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nodeestudos
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    container_name: postgres-db
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
